---
title: "Erdem_NN1"
format: html
editor: visual
---

## Install libraries

```{r}
#install.packages("drat", repos="https://cran.rstudio.com")
#drat:::addRepo("dmlc")
#install.packages("xgboost")
#install.packages("caret)
#install.packages("xgboost)
```

```{r}
library(tidyverse)
library(keras)
library(ggplot2)
library(xgboost)
library(fastDummies)
library(dplyr)
library(caret)
```

## Data Preparation

```{r}
train_data = readRDS("train.rds")
train_data
```

## EDA

## 

```{r}
train_data |> ggplot(aes(x=score)) +
  geom_histogram()
```

## Convert factors to dummy variables

```{r}
train_data_dummy <- dummy_cols(train_data,remove_first_dummy=TRUE,remove_selected_columns=TRUE)
train_data_dummy
```

## Sample train and test data

```{r}
set.seed(1)
sample <- sample(c(TRUE, FALSE), nrow(train_data_dummy), replace=TRUE, prob=c(0.8,0.2))
train  <- train_data_dummy[sample, ]
test   <- train_data_dummy[!sample, ]
```

## Train, test split

```{r}
X_train <- train[, -which(names(train) == "score")]
y_train <- data.frame(train$score)
X_test <- test[, -which(names(train) == "score")]
y_test <- test$score
```

```{r}
train
```

## EDA 
